(function(){
  const KEY='glpbuddy_app_state_v2', DISMISS_KEY='glpbuddy_photo_prompt_dismissed', DEMO_FLAG='glpbuddy_demo_seeded_v1';
  const breakfastPool=['Greek yoghurt bowl with berries','Eggs on whole wheat toast','Oats with cinnamon apple','Smoothie with yoghurt and oats','Yoghurt bowl with pineapple','Eggs with tomato on toast'];
  const lunchPool=['Chicken couscous bowl','Tuna wrap with lettuce','Leftover protein bowl','Chicken salad wrap','Tuna pasta salad','Lentil and veg soup'];
  const dinnerPool=['Chicken paella with peppers','Lean beef stir fry','Salmon with baby marrow and couscous','Braai chicken with butternut','Game meat stew with sweet potato','Turkey mince tomato pasta','White fish tray bake'];
  const weekdays=['Mon','Tue','Wed','Thu','Fri','Sat','Sun'];
  const ingredientMap={'Greek yoghurt bowl with berries':{'Greek yoghurt':'7 tubs','Berries':'7 cups','Seeds':'1 pack'},'Eggs on whole wheat toast':{'Eggs':'18','Whole wheat bread':'2 loaves','Tomatoes':'5'},'Oats with cinnamon apple':{'Oats':'1 bag','Apples':'7','Cinnamon':'1 jar'},'Smoothie with yoghurt and oats':{'Greek yoghurt':'5 tubs','Oats':'1 bag','Bananas':'7'},'Yoghurt bowl with pineapple':{'Greek yoghurt':'6 tubs','Pineapple':'2','Seeds':'1 pack'},'Eggs with tomato on toast':{'Eggs':'18','Whole wheat bread':'2 loaves','Tomatoes':'7'},'Chicken couscous bowl':{'Chicken breast':'1.5 kg','Couscous':'1 box','Mixed salad veg':'5 packs'},'Tuna wrap with lettuce':{'Tuna tins':'5','Whole wheat wraps':'2 packs','Lettuce':'2'},'Leftover protein bowl':{'Extra dinner portions':'planned','Mixed salad veg':'4 packs'},'Chicken salad wrap':{'Chicken breast':'1 kg','Whole wheat wraps':'2 packs','Lettuce':'2'},'Tuna pasta salad':{'Tuna tins':'4','Whole wheat pasta':'1 bag','Cucumber':'2'},'Lentil and veg soup':{'Lentils':'1 bag','Soup veg':'2 packs','Stock':'2 cubes'},'Chicken paella with peppers':{'Chicken breast':'1.2 kg','Rice':'1 bag','Peppers':'5'},'Lean beef stir fry':{'Lean beef strips':'1.2 kg','Broccoli':'3 heads','Stir-fry veg':'3 packs'},'Salmon with baby marrow and couscous':{'Salmon fillets':'6','Baby marrow':'8','Couscous':'1 box'},'Braai chicken with butternut':{'Chicken pieces':'1.8 kg','Butternut':'2','Spices':'1 set'},'Game meat stew with sweet potato':{'Game meat':'1.5 kg','Sweet potatoes':'8','Onions':'4'},'Turkey mince tomato pasta':{'Turkey mince':'1.2 kg','Whole wheat pasta':'1 bag','Tomato passata':'2 jars'},'White fish tray bake':{'White fish fillets':'6','Mixed veg':'3 packs','Olive oil':'1 bottle'}};
  function safeParse(v,f){try{return JSON.parse(v)}catch(e){return f}}
  function iso(d){return new Date(d).toISOString().slice(0,10)}
  function today(){return iso(new Date())}
  function uid(p){return (p||'id')+'_'+Math.random().toString(36).slice(2,10)}
  function addDays(dateStr,days){const d=new Date(dateStr+'T12:00:00'); d.setDate(d.getDate()+days); return iso(d)}
  function getState(){return safeParse(localStorage.getItem(KEY),null)}
  function saveState(s){localStorage.setItem(KEY,JSON.stringify(s)); return s}
  function samplePhoto(label,bg){return 'data:image/svg+xml;utf8,'+encodeURIComponent(`<svg xmlns="http://www.w3.org/2000/svg" width="700" height="1000" viewBox="0 0 700 1000"><rect width="700" height="1000" fill="${bg}"/><rect x="70" y="70" width="560" height="860" rx="36" fill="rgba(255,255,255,.32)" stroke="rgba(255,255,255,.65)"/><circle cx="350" cy="280" r="76" fill="rgba(255,255,255,.72)"/><rect x="260" y="360" width="180" height="260" rx="90" fill="rgba(255,255,255,.72)"/><rect x="208" y="395" width="58" height="220" rx="29" fill="rgba(255,255,255,.62)"/><rect x="434" y="395" width="58" height="220" rx="29" fill="rgba(255,255,255,.62)"/><rect x="290" y="610" width="50" height="220" rx="25" fill="rgba(255,255,255,.62)"/><rect x="360" y="610" width="50" height="220" rx="25" fill="rgba(255,255,255,.62)"/><text x="50%" y="90" text-anchor="middle" font-family="Arial" font-size="38" fill="#fff">${label}</text></svg>`)}
  function makeDemoState(){const startDate=addDays(today(),-180); const profile={name:'Sarah',age:40,gender:'Female',startWeight:92.6,goalWeight:74,medication:'Wegovy',dose:'1.0 mg',injectionDay:'Monday',units:'kg',theme:'Sage'}; const settings={photoFrequency:'biweekly',photoPrompts:true,reminders:true,backupMode:'local'}; const logs={}; let weight=profile.startWeight; const plateauStart=85, plateauEnd=120; for(let i=0;i<=180;i++){const date=addDays(startDate,i); const dow=new Date(date+'T12:00:00').getDay(); const shouldWeigh=!([2].includes(dow))&&Math.random()>0.18; const earlyDrop=i<plateauStart?0.08:0.03; const plateauEffect=(i>=plateauStart&&i<=plateauEnd)?-0.015:0; const jitter=(Math.random()-0.5)*0.26; weight=Math.max(77, +(weight-earlyDrop-plateauEffect+jitter).toFixed(1)); const symptoms=[]; if(i<28&&Math.random()>0.55)symptoms.push('Nausea'); if(i<60&&Math.random()>0.65)symptoms.push('Fatigue'); if(Math.random()>0.88)symptoms.push('Bloating'); if(Math.random()>0.93)symptoms.push('Headache'); const workoutDone=[1,3,5].includes(dow)&&Math.random()>0.28; const walkDone=[0,2,4,6].includes(dow)?Math.random()>0.18:Math.random()>0.35; logs[date]={date, weight:shouldWeigh?+weight.toFixed(1):null, mood:3+(Math.random()>0.55?1:0)-(Math.random()>0.92?1:0), energy:2+(Math.random()>0.4?1:0)-(symptoms.includes('Fatigue')?1:0), hunger:i<45?2:(Math.random()>0.5?2:3), water:Math.max(3,Math.min(9,Math.round(5+Math.random()*3))), workoutDone, walkDone, medicationTaken:dow===1, symptoms, note:symptoms.length?'A little off today, keeping things simple.':''}}
    const mealPlan={id:uid('mealplan'),createdDate:addDays(today(),-2),lockedMeals:['Mon_dinner','Wed_lunch'],days:{Mon:{breakfast:'Greek yoghurt bowl with berries',lunch:'Chicken wrap with salad',dinner:'Beef mince bolognese with whole wheat pasta'},Tue:{breakfast:'Eggs on whole wheat toast',lunch:'Leftover bolognese bowl',dinner:'Chicken paella with peppers'},Wed:{breakfast:'Oats with yoghurt and banana',lunch:'Tuna salad bowl',dinner:'Salmon with baby marrow and couscous'},Thu:{breakfast:'Smoothie with yoghurt and oats',lunch:'Chicken couscous bowl',dinner:'Lean beef stir fry'},Fri:{breakfast:'Eggs and tomato on toast',lunch:'Leftover stir fry lunch bowl',dinner:'Calamari pan with rice'},Sat:{breakfast:'Yoghurt bowl with pineapple',lunch:'Chicken salad wrap',dinner:'Braai chicken with butternut'},Sun:{breakfast:'Oats with cinnamon apple',lunch:'Tuna pasta salad',dinner:'Game meat stew with sweet potato'}}};
    const photoDates=['2025-10-01','2025-10-15','2025-11-01','2025-11-15','2025-12-01','2025-12-15','2026-01-01','2026-01-15','2026-02-01','2026-02-15','2026-03-01'];
    const colors1=['#c58f8f','#bb9c75','#7da08f','#8e95c4'], colors2=['#9eb0cf','#9ec7bf','#d1a07a','#c69bb7'], colors3=['#7aa6b5','#b2b46d','#bc9292','#7f8db5'];
    const progressPhotos=photoDates.map((d,i)=>({id:uid('photo'),date:d,front:samplePhoto('Front • '+d,colors1[i%4]),side:samplePhoto('Side • '+d,colors2[i%4]),back:samplePhoto('Back • '+d,colors3[i%4]),note:i===0?'Starting point':(i===photoDates.length-1?'Feeling lighter and moving better':'Steady progress')}));
    const communityPosts=[{id:uid('post'),author:'Sarah',when:addDays(today(),-2),type:'win',text:'Hit my water goal 5 days in a row. Small win but it feels good.'},{id:uid('post'),author:'Nadine',when:addDays(today(),-5),type:'support',text:'Rough nausea day today, but still got a short walk in.'},{id:uid('post'),author:'Coach Tip',when:addDays(today(),-7),type:'tip',text:'Low appetite days still need protein. Keep something simple ready.'},{id:uid('post'),author:'Mia',when:addDays(today(),-9),type:'win',text:'Took my monthly photos today. So glad I did — the scale was not telling the full story.'}];
    const exercise={streakWeeks:6,levelSummary:'Building confidence',weeklyTarget:3,completedThisWeek:2,currentSession:{title:'Week 12 • Full Body Session A',approxMinutes:24,movements:['Chair / bodyweight squat','Wall push-up','Supported hinge','March in place','Bird-dog']},movementLevels:[{name:'Squat',level:'Bodyweight',next:'Narrow stance'},{name:'Push',level:'Wall push-up',next:'Counter push-up'},{name:'Hinge',level:'Supported hinge',next:'Tempo hinge'},{name:'Core',level:'Dead bug',next:'Bird-dog'}]};
    return {profile,settings,dailyLogs:logs,mealPlan,progressPhotos,communityPosts,exercise};
  }
  function ensureSeeded(force){const url=new URL(location.href); if(force||url.searchParams.get('demo')==='1'||!getState()){saveState(makeDemoState()); localStorage.setItem(DEMO_FLAG,'1')}}
  function getProfile(){return (getState()||{}).profile||{}}
  function saveProfile(p){const s=getState()||makeDemoState(); s.profile=Object.assign({},s.profile,p); saveState(s)}
  function getSettings(){return (getState()||{}).settings||{}}
  function saveSettings(v){const s=getState()||makeDemoState(); s.settings=Object.assign({},s.settings,v); saveState(s)}
  function getDailyLogs(){return (getState()||{}).dailyLogs||{}}
  function getLog(date){date=date||today(); return getDailyLogs()[date]||{date,weight:null,mood:null,energy:null,hunger:null,water:0,workoutDone:false,walkDone:false,medicationTaken:false,symptoms:[]}}
  function saveLog(date,patch){const s=getState()||makeDemoState(); const current=s.dailyLogs[date]||getLog(date); s.dailyLogs[date]=Object.assign({},current,patch,{date}); saveState(s)}
  function getMealPlan(){return (getState()||{}).mealPlan||null}
  function saveMealPlan(plan){const s=getState()||makeDemoState(); s.mealPlan=plan; saveState(s)}
  function generateMealPlan(existing){const prev=existing||getMealPlan()||{lockedMeals:[],days:{}}; const locked=new Set(prev.lockedMeals||[]); const days={}; weekdays.forEach(function(day,idx){const prior=prev.days&&prev.days[day]?prev.days[day]:{}; days[day]={}; ['breakfast','lunch','dinner'].forEach(function(slot){const key=day+'_'+slot; if(locked.has(key)&&prior[slot]){days[day][slot]=prior[slot]; return;} const pool=slot==='breakfast'?breakfastPool:(slot==='lunch'?lunchPool:dinnerPool); days[day][slot]=pool[(idx+Math.floor(Math.random()*pool.length))%pool.length];})}); const plan={id:uid('mealplan'),createdDate:today(),lockedMeals:Array.from(locked),days}; saveMealPlan(plan); return plan}
  function toggleMealLock(day,slot){const plan=getMealPlan()||generateMealPlan(); const key=day+'_'+slot; const set=new Set(plan.lockedMeals||[]); if(set.has(key)) set.delete(key); else set.add(key); plan.lockedMeals=Array.from(set); saveMealPlan(plan); return plan}
  function regenerateMeal(day,slot){const plan=getMealPlan()||generateMealPlan(); const key=day+'_'+slot; const set=new Set(plan.lockedMeals||[]); set.delete(key); plan.lockedMeals=Array.from(set); const pool=slot==='breakfast'?breakfastPool:(slot==='lunch'?lunchPool:dinnerPool); plan.days[day][slot]=pool[Math.floor(Math.random()*pool.length)]; saveMealPlan(plan); return plan}
  function shoppingList(mode){mode=mode||'week'; const plan=getMealPlan()||generateMealPlan(); const tally={}; Object.values(plan.days).forEach(day=>{Object.values(day).forEach(meal=>{const items=ingredientMap[meal]||{}; Object.entries(items).forEach(([k,v])=>{if(!tally[k]) tally[k]=new Set(); tally[k].add(v);})})}); const list=Object.entries(tally).map(([name,vals])=>({name,qty:Array.from(vals).join(' + ')})); return mode==='month'?list.map(x=>({name:x.name,qty:'4 × '+x.qty})):list}
  function getProgressPhotos(){return ((getState()||{}).progressPhotos||[]).slice().sort((a,b)=>a.date.localeCompare(b.date))}
  function saveProgressPhotoSet(set){const s=getState()||makeDemoState(); s.progressPhotos=(s.progressPhotos||[]).filter(x=>x.date!==set.date); s.progressPhotos.push(Object.assign({id:uid('photo')},set)); s.progressPhotos.sort((a,b)=>a.date.localeCompare(b.date)); saveState(s)}
  function getCommunityPosts(){return ((getState()||{}).communityPosts||[]).slice().sort((a,b)=>b.when.localeCompare(a.when))}
  function addCommunityPost(post){const s=getState()||makeDemoState(); s.communityPosts=s.communityPosts||[]; s.communityPosts.unshift(Object.assign({id:uid('post'),when:today()},post)); saveState(s)}
  function getExercise(){return (getState()||{}).exercise||{}}
  function getWeights(limitDays){limitDays=limitDays||180; const cutoff=addDays(today(),-limitDays); return Object.values(getDailyLogs()).filter(x=>x.weight!=null&&x.date>=cutoff).sort((a,b)=>a.date.localeCompare(b.date))}
  function progressSummary(){const profile=getProfile(); const weights=getWeights(365); const current=weights.length?weights[weights.length-1].weight:null; const first=weights.length?weights[0].weight:profile.startWeight||null; const change=current!=null&&first!=null?+(current-first).toFixed(1):null; const towardGoal=current!=null&&profile.goalWeight?Math.max(0,Math.min(100,Math.round(((profile.startWeight-current)/(profile.startWeight-profile.goalWeight))*100))):0; let streak=0; for(let i=0;i<365;i++){const d=addDays(today(),-i); if(getLog(d).weight!=null) streak++; else break} return {current,first,change,weighIns:weights.length,towardGoal,streak}}
  function lastPhotoDate(){const arr=getProgressPhotos(); return arr.length?arr[arr.length-1].date:null}
  function nextPhotoDue(){const settings=getSettings(); const last=lastPhotoDate(); const freq=settings.photoFrequency||'biweekly'; if(freq==='off') return null; if(!last) return today(); return addDays(last,freq==='monthly'?30:14)}
  function photoReminderState(){const due=nextPhotoDue(); if(!due) return {show:false}; const dismissed=localStorage.getItem(DISMISS_KEY); return {show:(due<=today()&&dismissed!==today()),due}}
  function dismissPhotoPrompt(untilTomorrow){localStorage.setItem(DISMISS_KEY, untilTomorrow?addDays(today(),1):today())}
  function exportMealPlanMailto(){const plan=getMealPlan()||generateMealPlan(); const weekList=shoppingList('week').map(x=>`- ${x.name}: ${x.qty}`).join('%0D%0A'); const body=Object.entries(plan.days).map(([day,meals])=>`${day}%0D%0ABreakfast: ${meals.breakfast}%0D%0ALunch: ${meals.lunch}%0D%0ADinner: ${meals.dinner}`).join('%0D%0A%0D%0A'); location.href=`mailto:?subject=GLP Buddy meal plan&body=${body}%0D%0A%0D%0AShopping list%0D%0A${weekList}`}
  function renderLineChart(canvas,points){if(!canvas) return; const ctx=canvas.getContext('2d'), w=canvas.width, h=canvas.height; ctx.clearRect(0,0,w,h); ctx.fillStyle='#f7f4ef'; ctx.fillRect(0,0,w,h); if(!points.length){ctx.fillStyle='#6b7280'; ctx.font='14px sans-serif'; ctx.fillText('No weight data yet',20,40); return;} const vals=points.map(p=>p.weight); const min=Math.min(...vals)-1, max=Math.max(...vals)+1, pad=28; ctx.strokeStyle='#d7d1c8'; ctx.lineWidth=1; for(let i=0;i<4;i++){const y=pad+i*(h-pad*2)/3; ctx.beginPath(); ctx.moveTo(pad,y); ctx.lineTo(w-pad,y); ctx.stroke();} ctx.strokeStyle='#5d7f70'; ctx.lineWidth=3; ctx.beginPath(); points.forEach((p,i)=>{const x=pad+(i*(w-pad*2)/Math.max(1,points.length-1)); const y=h-pad-((p.weight-min)/(max-min))*(h-pad*2); if(i===0) ctx.moveTo(x,y); else ctx.lineTo(x,y)}); ctx.stroke(); ctx.fillStyle='#2f463d'; points.forEach((p,i)=>{if(i%Math.ceil(points.length/6)===0||i===points.length-1){const x=pad+(i*(w-pad*2)/Math.max(1,points.length-1)); ctx.fillText(p.date.slice(5),Math.max(6,x-14),h-8)}})}
  window.GLPStore={ensureSeeded,getState,saveState,getProfile,saveProfile,getSettings,saveSettings,getDailyLogs,getLog,saveLog,getMealPlan,saveMealPlan,generateMealPlan,toggleMealLock,regenerateMeal,shoppingList,getProgressPhotos,saveProgressPhotoSet,getCommunityPosts,addCommunityPost,getExercise,getWeights,progressSummary,nextPhotoDue,photoReminderState,dismissPhotoPrompt,exportMealPlanMailto,renderLineChart,today,addDays};
})();